### ISSUE TITLE
Long job submission time

### ISSUE THREAD

**Issue by anfie** [bgruening/docker-galaxy-imaging#7]
Hello,
I have been testing the Docker Imaging Galaxy lately. The instance itself could be created, but I got stucked while uploading data (200 kb JPG).  The entry appeared in the history as grey box ("This is a new dataset and not all of its data are available yet") and remained in this state for hours. Three hours (and heavy server communication) later, the job finished succesfully. These extremly long runtimes seem to be a common problem. Here are some snippets from the log file:

- Job submission:

galaxy.tools.execute DEBUG 2016-11-30 16:49:02,378 Tool [upload1] created job [1] (2515.271 ms)

- Job execution:

galaxy.jobs.runners.drmaa DEBUG 2016-11-30 20:13:56,412 (1/2) state change: job finished normally
galaxy.model.metadata DEBUG 2016-11-30 20:13:56,480 loading metadata from file for: HistoryDatasetAssociation 1
galaxy.jobs INFO 2016-11-30 20:13:56,770 Collecting metrics for Job 1
galaxy.jobs DEBUG 2016-11-30 20:13:56,876 job 1 ended (finish() executed in (446.705 ms))
galaxy.model.metadata DEBUG 2016-11-30 20:13:56,877 Cleaning up external metadata files

Taking a look in the job information, galaxy claimed the following runtime:
Job Start Time	2016-11-30 20:13:52
Job End Time	2016-11-30 20:13:55
, which appears to be more reasonable. Do you have any suggestions about this big delay between submission and execution of the jobs?
The docker image is running on a  8 core machine for testing...shall we move it to a bigger system? 

I will attach the shortened log file. It also documents some errors regarding slurm/condor.

Regards,
Anne

[imaging_log.txt](https://github.com/bgruening/docker-galaxy-imaging/files/624166/imaging_log.txt)

**Comment by bgruening** [comment]
Hi Anne,
a bigger machine is not needed. Can you confirm that this also happens with the second file?

**Comment by anfie** [comment]
Hallo Björn,
I tried to upload another 200 kb picture - the same problems.

- Submission

==> /home/galaxy/logs/handler0.log <==

> galaxy.jobs DEBUG 2016-12-01 **10:39**:18,366 (3) Working directory for job is: /export/galaxy-central/database/job_working_directory/000/3
> galaxy.jobs.handler DEBUG 2016-12-01 10:39:18,678 (3) Dispatching to slurm runner
> galaxy.jobs DEBUG 2016-12-01 10:39:19,285 (3) Persisting job destination (destination id: slurm_cluster)
> galaxy.jobs.runners DEBUG 2016-12-01 10:39:19,548 Job [3] queued (828.820 ms)
> galaxy.jobs.handler INFO 2016-12-01 10:39:19,572 (3) Job dispatched
> galaxy.tools.deps DEBUG 2016-12-01 10:39:20,138 Building dependency shell command for dependency 'samtools'
> galaxy.tools.deps DEBUG 2016-12-01 10:39:20,138 Find dependency samtools version None

- execution

> galaxy.jobs.runners DEBUG 2016-12-01 14:03:36,467 (3) command is: mkdir -p working; cd working; /export/galaxy-central/database/job_working_directory/000/3/tool_script.sh; return_code=$?; cd '/export/galaxy-central/database/job_working_directory/000/3'; python "/export/galaxy-central/database/job_working_directory/000/3/set_metadata_6GzY5Z.py" "/export/galaxy-central/database/files/tmptkw1Fp" "/export/galaxy-central/database/job_working_directory/000/3/working/galaxy.json" "/export/galaxy-central/database/job_working_directory/000/3/metadata_in_HistoryDatasetAssociation_2_0TJawb,/export/galaxy-central/database/job_working_directory/000/3/metadata_kwds_HistoryDatasetAssociation_2_PqaSmg,/export/galaxy-central/database/job_working_directory/000/3/metadata_out_HistoryDatasetAssociation_2_Aykgf9,/export/galaxy-central/database/job_working_directory/000/3/metadata_results_HistoryDatasetAssociation_2_1ZH1UR,/export/galaxy-central/database/files/000/dataset_2.dat,/export/galaxy-central/database/job_working_directory/000/3/metadata_override_HistoryDatasetAssociation_2_xTXtV1" 5242880; sh -c "exit $return_code"
> galaxy.jobs.runners.drmaa DEBUG 2016-12-01 14:03:36,678 (3) submitting file /export/galaxy-central/database/job_working_directory/000/3/galaxy_3.sh
> galaxy.jobs.runners.drmaa DEBUG 2016-12-01 14:03:36,678 (3) native specification is: --ntasks=1 --share
> 
> ==> /home/galaxy/logs/uwsgi.log <==
> 192.168.32.33 - - [01/Dec/2016:14:03:36 +0000] "GET /api/histories/f2db41e1fa331b3e/contents?v=dev&q=update_time-ge&qv=2016-12-01T14%3A03%3A32.000Z HTTP/1.1" 200 - "http://194.94.139.22:8080/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
> [pid: 189|app: 0|req: 5032/7645] 192.16.32.33 () {46 vars in 954 bytes} [Thu Dec  1 14:03:36 2016] GET /api/histories/f2db41e1fa331b3e/contents?v=dev&q=update_time-ge&qv=2016-12-01T14%3A03%3A32.000Z => generated 2 bytes in 34 msecs (HTTP/1.1 200) 3 headers in 124 bytes (1 switches on core 2)
> 
> ==> /home/galaxy/logs/slurmctld.log <==
> [2016-12-01T14:03:37.279] _slurm_rpc_submit_batch_job JobId=4 usec=19791
> 
> ==> /home/galaxy/logs/handler0.log <==
> galaxy.jobs.runners.drmaa INFO 2016-12-01 14:03:37,279 (3) queued as 4
> galaxy.jobs DEBUG 2016-12-01 14:03:37,280 (3) Persisting job destination (destination id: slurm_cluster)
> 
> ==> /home/galaxy/logs/slurmctld.log <==
> [2016-12-01T14:03:37.280] sched: Allocate JobId=4 NodeList=0062464d43e4 #CPUs=1
> 
> ==> /home/galaxy/logs/slurmd.log <==
> [2016-12-01T14:03:37.719] Launching batch job 4 for UID 1450
> [2016-12-01T14:03:37.766] Received cpu frequency information for 8 cpus
> 
> ==> /home/galaxy/logs/handler0.log <==
> galaxy.jobs.runners.drmaa DEBUG 2016-12-01 14:03:38,720 (3/4) state change: job is running
> 
> ==> /home/galaxy/logs/uwsgi.log <==
> 192.168.32.33 - - [01/Dec/2016:14:03:40 +0000] "GET /api/histories/f2db41e1fa331b3e/contents?v=dev&q=update_time-ge&qv=2016-12-01T14%3A03%3A36.000Z HTTP/1.1" 200 - "http://194.94.13.226:8080/" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0"
> [pid: 189|app: 0|req: 5033/7646] 192.168.32.33 () {46 vars in 954 bytes} [Thu Dec  1 14:03:40 2016] GET /api/histories/f2db41e1fa331b3e/contents?v=dev&q=update_time-ge&qv=2016-12-01T14%3A03%3A36.000Z => generated 2 bytes in 16 msecs (HTTP/1.1 200) 3 headers in 124 bytes (1 switches on core 3)
> 
> ==> /home/galaxy/logs/slurmd.log <==
> [2016-12-01T14:03:41.810] [4] sending REQUEST_COMPLETE_BATCH_SCRIPT, error:0
> 
> ==> /home/galaxy/logs/slurmctld.log <==
> [2016-12-01T14:03:41.812] completing job 4
> [2016-12-01T14:03:41.814] sched: job_complete for JobId=4 successful, exit code=0
> 
> ==> /home/galaxy/logs/slurmd.log <==
> [2016-12-01T14:03:41.814] [4] done with job
> 
> ==> /home/galaxy/logs/handler0.log <==
> galaxy.jobs.runners.drmaa DEBUG 2016-12-01 14:03:42,490 (3/4) state change: job finished normally
> galaxy.model.metadata DEBUG 2016-12-01 14:03:42,709 loading metadata from file for: HistoryDatasetAssociation 2
> galaxy.jobs INFO 2016-12-01 14:03:43,419 Collecting metrics for Job 3
> galaxy.jobs DEBUG 2016-12-01 **14:03**:43,529 job 3 ended (finish() executed in (1015.809 ms))
> galaxy.model.metadata DEBUG 2016-12-01 14:03:43,531 Cleaning up external metadata files

I justed startet a second docker image on a VM, but problem seem to remain (upload running since half an hour).  The log file reports several errors in the "slurmctld.log". If you have a log file of an instance with a normal job performance, we can find out the reason for this behaviour.

**Comment by bgruening** [comment]
@anfie we just released a new version, 18.09. Please let us know if this does not work.
